### PR TITLE
Attempt re-merge of pa-categorize-standards

### PR DESCRIPTION
**Pull request by cgreene**
Seeing if this will give an avenue to a successful merge.

### CODE REVIEW

**Comment by cgreene** [comment]
@dhimmel - the goal here was to apply the commits from @agapow to the current master. Previously this was coming via #349 but there were a couple merges there that reverted existing changes to master. I've rebased @agapow's important commits to master before pushing this and it now appears to be correct. This has already been reviewed and should be considered approved. What's the best way to get this merged while making sure credit for the changes goes to @agapow?

**Comment by dhimmel** [comment]
Since you have multiple commits by multiple authors, I suggest using a "Create a merge commit" option to merge this. If you'd like to squash all three of @agapow's commits together for cleanliness, you can do that locally. However, I don't think that's necessary in this case, especially since @agapow wrote nice commit messages.

**Comment by agitter** [comment]
Do you need a review from @agapow or I, or is this still a work in progress?

**Comment by dhimmel** [comment]
> Do you need a review from @agapow or I, or is this still a work in progress?

Casey removed WIP from the title. Perhaps @agapow should verify all his changes from #349 are here.

**Comment by cgreene** [comment]
Going to merge this in the interests of making moving on to other PRs easier. @agapow - please file another PR if you find something was missed. Thanks!

**Comment by agapow** [comment]
Looks good. Go for it.

**Comment by dhimmel** [comment]
@cgreene in the future work off branches on your personal repo. Deleting `greenelab:pre-merge-pa`

**Pull request merged**
