### PR TITLE
Update Manubot on 2018-11-15

### PR DESCRIPTION
**Pull request by agitter**
@dhimmel I updated based on the [rootstock instructions](https://github.com/greenelab/manubot-rootstock/blob/master/SETUP.md#merging-upstream-manubot-rootstock-changes).  That looks like it is different from the way you have updated in the past because this created a single new commit.

Merging this should fix the PMC-related build error in #938.

### CODE REVIEW

**Comment by dhimmel** [comment]
Hmm not sure why all the commits are squashed. I don't think we want this because it may make determining which commits need merging in the future more difficult.

So you ran this?

```
git pull --no-ff --no-commit rootstock master
```

And nothing else besides resolving conflicts and then doing `git commit`?

I can try if you can't get the other behavior, but I'm curious what is happening.

**Comment by agitter** [comment]
I'm sure it was some error on my side, possibly because I started on my master branch and then realized I wanted a new branch for the pull request.  My process was

```
git pull --no-ff --no-commit rootstock master
```
That created conflicts, specifically two rootstock files that are not in deep-review and needed to be deleted.
```
git rm SETUP.md
git rm content/02.delete-me.md
```
Then I realized I was still on master
```
git checkout -b manubot
git commit -m "Update Manubot"
git push agitter manubot
```

I can close this pull request, but I'm interesting in figuring out what went wrong so I can get it right next time and potentially update the rootstock instructions.

**Comment by dhimmel** [comment]
Ah perhaps it was the change of branch with `--no-commit` that resulted in the new branch just having the changed files without the in-progress merge.

No need to close this PR. you can fix it on this branch. `git reset --hard` to the last good commit and then do the entire pull command there.

Do you think SETUP.md needs to be more clear?

**Comment by agitter** [comment]
> No need to close this PR. you can fix it on this branch.

Yes that worked.  As a reminder to my future self, this is specifically what I did from my `manubot` branch:
```
git reset --hard 939920570a269bd750af13286f8a053f08ffdaf8
git pull --no-ff --no-commit rootstock master
git rm SETUP.md
git rm content/02.delete-me.md
git commit -m "Updgrade Manubot on 2018-11-16"
git push -f agitter manubot
```

I agree we should add details to the rootstock setup, including instructions for updating Manubot via pull request.  Eventually, we expect a number of novice git users to be maintaining rootstock-derived repositories.

Have you been using `Rebase and merge` for these Manubot updates?

**Comment by dhimmel** [comment]
> Have you been using Rebase and merge for these Manubot updates?

No it's very important NOT TO USE GitHub's "rebase and merge" option here. That will change the commit hashes which can make future updates harder. Use "Merge pull request".

**Comment by agitter** [comment]
> No it's very important NOT TO USE GitHub's "rebase and merge" option here.

Got it.  Will use "Merge pull request".  That is also something we can add to the rootstock instructions.

**Pull request merged**
