### PR TITLE
Add JRSI citation to readme

### LINKED ISSUE #850: README should include recommended citation and link at the top
Encourages people to cite the paper properly. See https://segway.hoffmanlab.org/ for an example of what I have in mind.

### PR DESCRIPTION
**Pull request by agitter**
Closes #850 

@michaelmhoffman is this what you had in mind?

### CODE REVIEW

**Comment by michaelmhoffman** [comment]
Basically, although I would personally put it at the very top. This is fine though.

**Comment by agitter** [comment]
I updated the DOI in the front matter as well.

@stephenra and @evancofer this should be fast to review when you get a chance.

**Comment by stephenra** [comment]
@agitter Thanks. 

LGTM.

**Comment by evancofer** [comment]
LGTM.

**Comment by stephenra** [comment]
Thanks @evancofer. Apologies for the premature merge!

**Comment by dhimmel** [comment]
@stephenra @evancofer I'd recommend [squash merging](https://blog.github.com/2016-04-01-squash-your-commits/) PRs like this to keep the commit history as simple and linear as possible.

**Comment by stephenra** [comment]
Sure. Thanks @dhimmel.

**Pull request merged**
