### PR TITLE
fix the discussions of adversarial/augmented training

### PR DESCRIPTION
**Pull request by cgreene**

### CODE REVIEW

**Comment by cgreene** [comment]
@alxndrkalinin - here's the set of proposed edits if you want to review!

**Comment by alxndrkalinin** [comment]
Looks good 👍 

On a related note: we recently had 2 pre-prints using DL on small medical imaging datasets: massive augmentation  approach for breast cancer (https://doi.org/10.1101/259911); and segmentation without original ground truth (https://doi.org/10.1101/234120) for bone age prediction.
I think these would be a good addition to this small medical image data discussion – can make a PR if of interest.

**Comment by cgreene** [comment]
@alxndrkalinin : If you want to file a very small PR that touches a couple lines, I'm happy to take a look at them. Going to merge this one quickly now so we can move along the mandatory-for-resubmission items.

**Comment by alxndrkalinin** [comment]
@cgreene: just sent a small PR, #826

**Pull request merged**
