### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Benjamin-Lee**
ICJME -> ICMJE

### CODE REVIEW

**Comment by agitter** [comment]
The Travis build failed:
```
## ERROR
Citeproc retrieval failed for:
pmcid:PMC3041534
pmcid:PMC3797550
pmcid:PMC4765623
pmcid:PMC4832129
pmcid:PMC4907892
pmcid:PMC5119627
```

Let's wait to merge this to see if the PMCID citeproc retrieval error is only temporary.

**Comment by agitter** [comment]
We can check on the PMCID status directly using https://www.ncbi.nlm.nih.gov/pmc/utils/ctxp?ids=PMC4832129&report=citeproc instead of restarting the Travis build.  The utils site is still down.

**Comment by dhimmel** [comment]
I restarted the build.

**Comment by agitter** [comment]
👍 build passes now so I'll merge.

**Pull request merged**
