### PR TITLE
Update 03_categorize.md

### PR DESCRIPTION
**Pull request by traversc**
Changes by @XieConnect and @traversc

### CODE REVIEW

**Comment by traversc** [comment]
@cgreene (and @XieConnect) As you asked, I incorporated the changes that is up to date with the master repository.  I read the tutorial you linked to, but rebasing the original pull request was somewhat complicated because the pull request and master are different repositories not just different branches, so I made a whole new pull request and incorporated the changes manually.

**Comment by cgreene** [comment]
Thanks @traversc! Can you take a quick look at the codeclimate issues above. The line length ones in particular can make it hard to make comments on a pull request. I use the `atom` editor, which includes a "reflow selection" command that can automatically make 80 character lines. Can you go ahead and do that (or whatever the equivalent step is in your editor) so that we can get it reviewed?

**Comment by cgreene** [comment]
@traversc - can you revert the most recent commit and only reflow the specific paragraphs that you worked on? Reflow doesn't understand markdown well, and it'll mangle lists and everything else. Sorry - I should have mentioned that selecting only what you want to reflow is important. Thanks!

**Comment by traversc** [comment]
Done!  I reverted it and reflowed only the new sections.

**Comment by cgreene** [comment]
Ok - I'm going to try to handle @xieconnect's #194 first. These two sections are nicely related to each other. Once @XieConnect gets those changes made and we can incorporate that section, I'll come back to this one to make sure they work together.

**Comment by cgreene** [comment]
Ok - I think I got this one too. Going to work on the flow and section tomorrow.

**Pull request merged**
