### PR TITLE
`F1`/`F-measure` -> `F~1~ score`

### PR DESCRIPTION
**Pull request by michaelmhoffman**
Addresses greenelab/deep-review#602.

### CODE REVIEW

**Comment by agitter** [comment]
@dhimmel do we know how pandoc will render this?  Github flavored Markdown coverts it to strikethrough: F~1~

**Comment by dhimmel** [comment]
Probably not as intended. I'd suggest using the unicode subscript 1, like F₁ (copy and paste it). You could also do `<sub>1</sub>`.

**Comment by michaelmhoffman** [comment]
I didn't read this section of the Pandoc manual carefully enough. Looks like you may need the `subscript` extension enabled for this to work. That it breaks the Github-flavored Markdown is bad. Will try Unicode subscript 1.

https://pandoc.org/MANUAL.html#superscripts-and-subscripts

**Comment by agitter** [comment]
I didn't build the manuscript locally to test it, but I'll fix this if the Travis build looks bad after merging.

**Comment by agitter** [comment]
The build finally finished, and the Unicode subscript 1 works.

**Pull request merged**
