### PR TITLE
Move "wide" data stub from categorize -> discussion

### PR DESCRIPTION
**Pull request by cgreene**
Quick PR to just put the subsection into the right place.

### CODE REVIEW

**Comment by agitter** [comment]
Looks good to me.  I'll merge.

**Comment by agitter** [comment]
@cgreene @brettbj Do you know whether anyone plans to write this in the next few days?  I don't have much to say about this topic.

**Comment by cgreene** [comment]
@agitter : did this come up in treat or study at all? It's pretty extensively handled in:
 ###### Generating ground-truth labels can be expensive or impossible

If this only affects the categorize section, I think we can safely remove it now.

**Comment by agitter** [comment]
I don't believe any of the study sub-sections discuss this.  It came up in the issues for study-related papers much earlier.

I'm okay dropping it when I make my next Discussion pull request since no one has drafted it yet.

**Comment by cgreene** [comment]
That works for me. We've hammered on it for most of categorize. Thanks!

**Pull request merged**
