### PR TITLE
suggest adding a word cloud figure in intro section

### PR DESCRIPTION
**Pull request by luzh2**

### CODE REVIEW

**Comment by agitter** [comment]
Interesting idea.  What do we want the reader to learn from this figure?  It's pretty, but I don't see how it contributes to our message.

**Comment by agitter** [comment]
@luzh2 I'm going to close this unless you have more thoughts on how this figure contributes to our message.

**Comment by luzh2** [comment]
Dear Anthony,

Sorry that I missed your comment earlier. Please feel free to close this
specific one. I was hoping to generate some figure that could be seen as an
overview of the entire article; something that people could use in their
presentation. We created one for the bionlp section. Will have to think
more on this general one. Thanks!

Zhiyong

**Comment by agitter** [comment]
Thanks @luzh2, and we do still plan to review your NLP section #567.

**Pull request closed without merging**
