### PR TITLE
Update tags.tsv with placeholder references

### PR DESCRIPTION
**Pull request by dhimmel**
See https://github.com/greenelab/deep-review/issues/262.

@gailrosen, I'm creating this pull request with your additions to tags.tsv.

### CODE REVIEW

**Comment by dhimmel** [comment]
@gailrosen this pull request is going to be difficult to merge... it has conflicts and needs to be rebased on the latest repo version. I'll try to take care of this and will mention you if I have any questions about the references.

**Comment by dhimmel** [comment]
Moved to https://github.com/greenelab/deep-review/pull/277.

**Comment by gailrosen** [comment]
thanks for making it standardized.  there are a few references that i need to change from [ref] to something i called in the references file -- so let me know.  thanks -Gail

**Comment by dhimmel** [comment]
> there are a few references that i need to change from `[ref]` to something i called in the references file

@gailrosen let's do that after #277 is merged.

**Comment by agitter** [comment]
> Moved to #277.

@dhimmel Moved to #278?  I think I follow your merge strategy but want to make sure I'm keeping up.

**Comment by dhimmel** [comment]
@agitter, I had mistyped. Edited my comments to fix the reference.

**Pull request closed without merging**
