### PR TITLE
Condense NLP section

### PR DESCRIPTION
**Pull request by agitter**
Following up on #567, I tried to condense some of the NLP section in categorize without losing any of the main points.  There were also several inconsistent acronyms.  @luzh2 can you please review to make sure the edited version is still correct?

After we merge this, we need to fix the clinical EHR sections.  We now have an EHR paragraph in the text mining sub-section and a text mining paragraph in the following EHR sub-section.  They mention some of the same papers.  This should be collapsed, and we need a better transition from the text mining to EHR sub-sections.

### CODE REVIEW

**Comment by agitter** [comment]
A reference was dropped from the intro in #566.  I didn't want to make a separate pull request just for that so I'm adding it here.

**Comment by luzh2** [comment]
i have reviewed the edits on the NLP subsection and they look good to me. thanks

**Comment by agitter** [comment]
I'm going to merge this now that @luzh2 approved.

@luzh2 will you please be able to make another pull request to eliminate the redundant discussion between this section and the `Electronic health record` section?  There is too much overlap, but I don't have the right domain knowledge to merge these two sections.

**Comment by yfpeng** [comment]
Sure. I will work with @luzh2 to address this issue.

**Comment by agitter** [comment]
Thanks @luzh2 and @yfpeng.  I don't think it will be too hard.  Mostly a matter of deciding which section to delete the redundant text and references from.

**Pull request merged**
