### PR TITLE
Minor fix VAE table entry

### PR DESCRIPTION
**Pull request by stephenra**
Addressing #820:
>Minor point:
The description of the Variational Autoencoder in the glossary is slightly misleading. It is not trained to "learn normally-distributed features". A VAE rather learns a generative but only approximative probabilistic model of the data (which is often build on normal distributions but not necessarily so).

### CODE REVIEW

**Comment by dhimmel** [comment]
@stephenra is there a reason why you're changing the whitespace convention of the table? It's easiest here if you keep the changes restricted to what you're addressing.

**Comment by stephenra** [comment]
@dhimmel Sorry. Must have been the Markdown linting in my editor and didn't realize it. I can update the PR without whitespace changes.

**Comment by dhimmel** [comment]
> I can update the PR without whitespace changes if everything looks good?

Go ahead and revert the whitespace changes. Then another project maintainer will review the content changes.

**Comment by cgreene** [comment]
> Variational autoencoder (VAE) | This special type of generative AE learns a probabilistic latent variable model. | VAEs have been shown to often produce meaningful reduced representations in the imaging domain, and some early publications have used VAEs to analyze gene expression data.

**Comment by stephenra** [comment]
@cgreene @dhimmel LGTM. Thanks for the suggestions and correction. Will change PR shortly to reflect these changes.

**Comment by cgreene** [comment]
Ok - thanks @stephenra! Can you also add yourself to the acknowledgements section (with ORCID if possible)?

https://phylogenomics.blogspot.com/2018/03/calling-all-academics-help-improve.html

**Comment by stephenra** [comment]
Thanks @cgreene but for such a relatively minor contribution, I'm OK foregoing the acknowledgement. Hopefully, I can contribute in more meaningful ways in the near- and long-term.

**Comment by dhimmel** [comment]
> Advise to close and resubmit PR or revert commits?

Can you remove the additions to README and frontmatter, so that files changed only shows `content/02.intro.md`. Don't worry about the messy commit history. We're going to squash merge this anyway.

> I'm OK foregoing the acknowledgement. Hopefully, I can contribute in more meaningful ways in the near- and long-term.

I think we'd prefer if you added yourself to the acknowledgements (but only if you want to be there).

**Comment by stephenra** [comment]
Sure. Thanks @dhimmel.

**Comment by stephenra** [comment]
@dhimmel Cleaned up the commits and added myself to the acknowledgements.

**Pull request merged**
