### PR TITLE
Incorp sheldon temporal work as per #405

### PR DESCRIPTION
**Pull request by agapow**
Stepping in to do the small temporal work patch. Also rebroke-up the paragraph just above as it was a bit lump of text.

### CODE REVIEW

**Comment by agitter** [comment]
Thanks @agapow 

@cgreene how should we handle authors on this merge?

**Comment by agitter** [comment]
@agapow Thanks for picking up this abandoned pull request.  Can you please fetch the commits from #410 and rebase on those?  That way we'll have a record of who contributed what parts and @aaronsheldon's contribution.

**Comment by agapow** [comment]
Unfortunately I can't get to this tonite due to other work commitments and not being at my home computer. Could probably do it tomorrow morning (Europe time) if that helps.

**Comment by agitter** [comment]
I didn't check carefully.  Did you make additional improvements on top of #410?  I may be able to help merge #410 myself but don't want to miss your edits, if any.

**Comment by agapow** [comment]
There wa the responses to the PR that were incorporated as well.

**Comment by agitter** [comment]
@agapow I'm fairly confident that I was able to merge #410 and then this, resolving conflicts correctly.  If you see any problems post-merge, I'll be available to clean them up in the morning (US time).

**Comment by agapow** [comment]
Looks good.

**Pull request merged**
