### PR TITLE
Move interpretability paragraphs

### PR DESCRIPTION
**Pull request by agitter**
I'm moving the text @blengerich wrote in Treat to Discussion so that @akundaje can build on it.

### CODE REVIEW

**Comment by agitter** [comment]
@blengerich can you please see if I should move some of this text back to the Treat-specific section?  I didn't have much time right now to carefully divide what you wrote.

**Comment by agitter** [comment]
@blengerich I made a few more minor edits to help the text fit better in the general Discussion section and am now merging this so that others can build on it.  Please open a new pull request if you want to move some of the clinical-specific text back to the paragraphs you wrote in Treat, provide more context here, or otherwise repair some of my quick edits.

**Comment by blengerich** [comment]
Thanks, I agree this fits better in the discussion section. I think there are some subtle differences between interpretation for understanding v.s. interpretation for action, but this should be also included in the discussion section. I will write a short paragraph to clarify these thoughts.

**Comment by agitter** [comment]
Yes, that's an important distinction.  Thanks for offering to clarify my quick edits.

**Pull request merged**
