### PR TITLE
Update the Deep Review with latest Manubot

### PR DESCRIPTION
**Pull request by dhimmel**
Closes https://github.com/greenelab/deep-review/issues/680

### CODE REVIEW

**Comment by dhimmel** [comment]
You can browse what the repo will look like if this PR is merged at [this tree](https://github.com/dhimmel/deep-review/tree/12ce17cdfa572cca61f16457fa99e705826719c9).

Here's the PDF from a local build: [`manuscript.pdf`](https://github.com/greenelab/deep-review/files/1442331/manuscript.pdf).

Before merging remember to create `output` branch to replace `references` branch.

@agitter ready for review

**Comment by agitter** [comment]
@dhimmel I should have time to review this weekend

**Comment by dhimmel** [comment]
> I should have time to review this weekend

@agitter if okay with you, I recommend we merge now, since I anticipate people may begin making revisions this weekend and I don't want them to start off of the old repository.

I could then address any issues you identify in subsequent commits.

**Comment by agitter** [comment]
@dhimmel I can go through quickly now

**Comment by agitter** [comment]
@dhimmel should I create a new issue to track the items above that need to be fixed or double-checked?

**Comment by dhimmel** [comment]
> should I create a new issue to track the items above that need to be fixed or double-checked?

Yep, and you can assign me the ones you want me to do!

Some quick notes:

> Add back the example tag in USAGE.md

This seems like it should be an upstream manubot-rootstock change?

> Perhaps rename manuscript.pdf back to deep-review.pdf along with the other outputs

We could create a symlink pointing to `manuscript.pdf`. I'd only do this if we think there are public links (outside of this repo) to deep-review.pdf.

The arXiv build warnings are because those studies have now been published with DOIs. We can fix these at the end or sooner?

> Make a note to all authors about the changes such as the ; between multiple references and prohibited characters in citations

This should be partly done in the updated README.

**Comment by agitter** [comment]
> Add back the example tag in USAGE.md

We had a Deep Review-specific example, `[@tag:Zhou2015_deep_sea]`, that I had in mind.  Any example from `citation-tags.tsv` would be fine, in which case it wouldn't be in the upstream manubot-rootstock.

> Perhaps rename manuscript.pdf back to deep-review.pdf along with the other outputs

We can leave this alone.  It was only my very minor personal preference.

> The arXiv build warnings are because those studies have now been published with DOIs.

We could fix them now or immediately before resubmitting. I expect other preprints could be published.  I just don't want to forget to do it.

> This should be partly done in the updated README.

Your README update took care of the semi-colon.  I'll use my #696 for the forbidden tags.

**Pull request merged**
