### PR TITLE
Update 02_intro.md

### PR DESCRIPTION
**Pull request by traversc**
Proposed paragraph in introduction exploring type of biological problems people have looked at in the literature.

### CODE REVIEW

**Comment by agitter** [comment]
I generally support some form of introduction to the biomedical problems and data types that will be covered in the review.  Most of those will fall neatly into one of Study/Categorize/Treat and will be discussed more extensively in those sections.  Here, we can have a fairly short preview of what is to come.

I think we want to avoid enumerating methods in the style of "neural network architectures A, B, C have been applied to data types X, Y, Z" in both the intro and main sections.  That has been well-covered by existing reviews, and we hope to target this one more toward the guiding question of #88 and provide perspective.

I'll leave this open for a couple days to see if there are any comments from others.

**Comment by cgreene** [comment]
I agree with @agitter that we want to avoid enumerating either domains or architectures because there are reviews that already exist of that form and we were specifically asked not to do that by the journal:

> We intend the reviews to address critical developments in an area of cross-disciplinary research and, when possible, to place such research in a broader context. This is not a place for comprehensive literature surveys.

The additional language on the readme highlights an area that I think we can contribute - namely informed speculation.

> We do encourage you to speculate in an informed way, and to be topical and provocative about the subject without worrying unduly about space, (the provisional target length is 8 -12,000 words). Please think of this as an article which will be a landmark in your area, and will come to be considered as a classic paper of the literature.

**Comment by cgreene** [comment]
I do wonder if this would be better placed in the "study" section. I think we may want to discuss specific approaches largely within those to make the introduction and conclusion more speculative than specific-case driven (unless there's one or two that we really want to highlight). There is a bit of this discussion of application areas in our 'categorize' outline.

**Comment by agitter** [comment]
Regarding architectures, I think we need to say enough so that someone who isn't familiar with neural networks can appreciate why they are special (worthy of a review), why a CNN is different from a RNN, etc., but no more.

Regarding domains, it may be helpful to give a few examples in the intro to help reader understand what we mean by Categorize, Study, Treat.  The individual sections could expand on that.

**Comment by agitter** [comment]
Since there is no more discussion, I'll merge this with the caveats raised above:
* We don't want to enumerate domains or architectures
* A short, targeted discussion of the variety of problems will we present could help give our audience a preview of the scope of this review.  But most of the discussion of different application areas will fall within the Categorize, Study, Treat sections.

**Pull request merged**
