### PR TITLE
[WIP] 04_study: Transcription factors and RNA-binding proteins

### PR DESCRIPTION
**Pull request by jacklanchantin**
I'm writing the section on Transcription factors and RNA-binding proteins. I am planning on writing an intro paragraph explaining the task of predicting TFBSs and RNA-binding proteins, and then going into detail on each.

### Transcription Factor Proteins:
I think that below are the core papers related to TFBS prediction. I will start with a background explaining the task and ChIP-Seq. Then talk about the initial PWM consensus sequence/motif matching approaches, followed by SVMs, DeepBind, and the most deep learning approaches. I am planning on covering the DeepBind model, the flaws in its simple architecture, and then discuss deeper CNN models,  LSTMs, and CNN-LSTM models. 

Feel free to correct me, but in my opinion, a lot of the recent works make minor architectural changes, and claim a state-of-the-art model by showing a minor change in auROC score (which @akundaje pointed out isn't always the best). In many cases, it's really hard to tell what is "better" about the new model. I have seen this so commonly with computer vision and NLP papers, where someone may get a 0.1 increase in accuracy, but it's hard to tell if that's really a result of the model. That being said, I think it's hard to say what is "best" right now, but I do think that we captured a good summary of this in the Deep Motif Dashboard paper by explaining the key features of a CNN-LSTM, which works the best (which I can summarize here). I believe that the most important result is that pure motif matching isn't the best way to model TFBS. There are long range temporal dependencies.

In my experience with med school collaborations, the visualizations of the model predictions are just as important, if not more important than the individual predictions. #85 and #50 are two important visualization papers in this particular area. In terms of visualizing important nucleotides, #50 seems like a better approach than #85 . However, I think there are other visualization methods such as class optimization (i.e. motif generation) and temporal dependency visualizations, which I can discuss. I don't believe there is a "one size fits all" approach to visualizations. It depends on who is using the model.  @akundaje, what are your overall thoughts on this?

Next accomplishments: I think that so far, most of the work has been done on very defined ChIP-seq datasets where the sequences are all of the same length, they are doing binary prediction on a continuous ChIP-seq value, and they don't take into account multiple TFs binding in one place. In order to more accurately "simulate" functional genomic events, we need better prediction tasks and datasets. Considering a dataset that accounts for variable sequence length, does ChIP-seq regression rather than classification, and is a multi-class output, requires a much more complex model, but I think it needs to be considered.

- [ ] [DNA binding sites: representation and discovery (#233)](https://github.com/greenelab/deep-review/issues/233)
- [ ] [An assessment of neural network and statistical approaches for prediction of E. coli promoter sites. (#234)
](https://github.com/greenelab/deep-review/issues/234)
- [ ] [Enhanced Regulatory Sequence Prediction Using Gapped k-mer Features(#235)](https://github.com/greenelab/deep-review/issues/235)
- [ ] [SeqGL Identifies Context-Dependent Binding Signals in Genome-Wide Regulatory Element Maps
(#235)](https://github.com/greenelab/deep-review/issues/235)
- [ ] [Predicting the sequence specificities of DNA- and RNA-binding proteins by deep learning (#11)](https://github.com/greenelab/deep-review/issues/11)
- [ ] [Deep Motif Dashboard: Visualizing and Understanding Genomic Sequences Using Deep Neural Networks (#85)](https://github.com/greenelab/deep-review/issues/85)
- [ ] [Not Just a Black Box: Learning Important Features Through Propagating Activation Differences (#50)](https://github.com/greenelab/deep-review/issues/50)

### RNA-binding Proteins:

I am not as experienced with this as I have not done any experiments on this data, but I can try. Does anyone else have expertise in this. I know it's very similar to TFBS prediction.

### CODE REVIEW

**Comment by gwaygenomics** [comment]
@jacklanchantin I think that outline sounds great! I was thinking about contributing to the study section as well, but moreso in the `gene expression` domain - which I think also ties nicely into gene regulation and TFBS/RBPs. So I thought I would jump right in on this PR!

A couple points: 
1. How have we been dealing with algorithmic solutions "pre-deep learning revolution" applied to the field? i.e. how much do we want to discuss PWMs and SVMs?
2. I think it also you may want to make sure your `treat-screening` branch is up to date with the most recent greenelab master branch as there will probably be less headache to get material merged. I think this is why all of these commits are appearing. The [Network Graph](https://github.com/jacklanchantin/deep-review/network) may help figuring this out.

**Comment by jacklanchantin** [comment]
Thanks a lot for the comments @gwaygenomics. 

1. I think it's important to discuss PWMs in the sense that this is what biomedical researchers thought were the main influences of TFBSs. They believe that a TFBS is due to these consensus sequences which can be learned via PWMs in methods such as MEME. As for SVMs, I think that they are powerful in this domain if you have the right features, but the main issue is that they are so slow in testing. This is especially a problem when you may have to test hundreds of thousands of samples. 

2. Yes, you're right I completely screwed up the pull request. Let me fix that.

**Comment by gwaygenomics** [comment]
sounds good @jacklanchantin - I agree that its important to give context into how computational predictions have evolved. I think it may also be equally as important to prognosticate how far deep learning can go - something which may be a theme or flavor of our review and I think was done quite elegantly in the [morphological phenotypes](https://github.com/greenelab/deep-review/blob/master/sections/04_study.md#morphological-phenotypes) subsection.

Once you get the branches synced and have pieces of your section written please let me know - I'd be happy to review. I can also let you know when I submit a PR of my subsection!

**Comment by agitter** [comment]
@jacklanchantin your approach looks good to me.  You seem to be suggesting that there has been a short term "plateau" in performance, where architectural differences produce only small bumps in accuracy.  Am I reading that correctly?

We'll have a separate section on problems with ROC for evaluation with imbalanced classes so feel free to refer to that (to-be-written) section here.

For this review in particular, I think we should mention the line of work that seeks to use TF binding prediction to interpret non-coding genetic variation.  That could be a separate pull request though because you already have many papers to cover here.

**Comment by cgreene** [comment]
I like the path that you are taking with this. I think there is something a bit odd going on with this PR since it looks like any commits to master are getting moved to treat-screening. @jacklanchantin - Is this desired or should we re-setup this PR?

If you make your own fork, and then try to PR from your own fork into `greenelab/deep-review master` that might be the way to go.

**Comment by jacklanchantin** [comment]
Yeah, sorry I screwed up this PR. I need to reset it

**Comment by jacklanchantin** [comment]
@agitter . Yes, I agree. That would be along the lines of the DeepSEA paper right?

**Comment by agitter** [comment]
@jacklanchantin Yes, DeepSEA is one example.  There are others as well, though I don't recall which use deep learning and which use other approaches.

Either way, I think we can leave genetic variant interpretation as a TODO and work on merging a draft of this first.

**Pull request closed without merging**
