### PR TITLE
added metabolism section

### PR DESCRIPTION
**Pull request by swamidass**
Following discussion, this adds a new section on metabolism and renames HTS section to ligand-based bioactivity prediction.

### CODE REVIEW

**Comment by swamidass** [comment]
Not sure why that fails. It is a really simple change...

**Comment by swamidass** [comment]
Not sure why that fails. It is a very simple change.

**Comment by cgreene** [comment]
Ok - removed one of the blank lines to keep codeclimate happy. As far as codeclimate goes, that error is relatively minor. Mostly we're using it to flag >80chars/line contributions because these are very hard to comment on. @agitter - this is currently a title change - is it good to go in?

**Comment by agitter** [comment]
Yes, let's merge.  We may or may not have further refinement or need to add additional sub-sections as we continue the discussion in #174, but this matches our current mindset and allows @swamidass to start working on an independent pull request based on the text he left in the comments of #174.

**Pull request merged**
