### PR TITLE
Seeking to Merge DNA Methylation Background Section for More DNAm PRs

### PR DESCRIPTION
**Pull request by jlevy44**
Planning on adding at least two more paragraphs that expand on the points introduced in the last paragraph of this background statement. Will need help editing these points and making text more concise and accurate, also to leave room for remaining text. Also looking to adjust some text from the previous gene expression paragraphs, prior text involving deep learning and methylation (eg. Deep CpG), and text surrounding latent space arithmetic. See #942 for more information, though more deep learning and methylation papers have come out (or in preprint) since initial issue.

We will expand and fill out this section with at least two more PRs.

@AlexanderTitus, @Christensen-Lab and I will PR remaining text.

Suggested reviews from @cgreene and @evancofer . Thanks everyone!

### CODE REVIEW

**Comment by jlevy44** [comment]
Are you referencing the text I just sent in?

**Comment by AlexanderTitus** [comment]
> Are you referencing the text I just sent in?

Yes, the intro to the methylation section you submitted.

**Comment by jlevy44** [comment]
Got it. Should be done. Let me know if I missed something.

**Comment by agitter** [comment]
@evancofer @stephenra before you merge this, I recommend you finalize the author ordering decisions in #833.  When new authors are added in a pull request like this, are they immediately added to the author list?  Or do you want to have a staging area for new authors and then add them in a randomized order all at once?  Whatever you do, I suggest that it should be publicly visible that new contributors have been added.

**Comment by evancofer** [comment]
@agitter Unclear. I feel like the most reasonable approach for author ordering is for it to be staged, i.e. hierarchical within the new contributors for each version.

Also, I would love someone who is more familiar with the methylation field to give this a look over. I am totally swamped this week (qualifying exams Thursday).

**Comment by lanagarmire** [comment]
@jlevy44 I can help on editing the new PR on DNA methylation. Besides the deconvolution issue of DNA methylation without reference, in practice it is also important to predict DNA methylation from gene expression ans DNA sequencing, or vice versa. Practically, many tissue blocks you can still try DNA methylation but not RNAseq.

**Comment by jlevy44** [comment]
Wonderful, thanks @lanagarmire. @AlexanderTitus @Christensen-Lab and I will be PRing a few more subsections of the methylation section that contains very the paper you are referencing https://www.biorxiv.org/content/early/2018/12/09/491357 . 

This PR is just to add some motivational materials, so I think we could include a brief mention to GE+DNA sequencing -> DNAm here, but we have drafted material that expands on all of the enumerated points below. 

Feel free to edit, but I've listed the papers below that we plan to PR in our draft, we may want to leave them out of these background paragraphs, but I am open to ideas.

Just to let everyone know, here are the papers we plan to add/cite in our next two PRs (sections undergoing internal review before PR):
https://www.biorxiv.org/content/early/2018/08/06/385849
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-017-1189-z
https://www.biorxiv.org/content/early/2018/09/03/406066
https://ieeexplore.ieee.org/abstract/document/8325078/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4726425/
https://www.biorxiv.org/content/early/2018/12/09/491357
https://www.biorxiv.org/content/biorxiv/early/2018/10/14/438341.full.pdf
https://www.biorxiv.org/content/early/2018/10/09/438218 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5603430/ 
https://bmcproc.biomedcentral.com/articles/10.1186/s12919-018-0121-1 https://bmcgenet.biomedcentral.com/articles/10.1186/s12863-018-0646-3
https://arxiv.org/abs/1807.09617
https://arxiv.org/pdf/1810.01243.pdf
https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=7484730&tag=1 https://arxiv.org/abs/1808.01359
http://www.scitepress.org/DigitalLibrary/Link.aspx?doi=10.5220/0006636401400145 https://www.biorxiv.org/content/early/2018/11/07/433763
https://www.biorxiv.org/content/early/2018/08/05/385534

**Comment by AlexanderTitus** [comment]
We are planning to o submit two more pull requests to round out the whole methylation section so Brock, Josh and I can contribute.

The easiest process would to get this approved so we can submit the next ones. Can someone review and approve?

**Comment by agitter** [comment]
@AlexanderTitus @jlevy44 it looks like no one with the right expertise is able to review this immediately.

Are you able to proceed with the pull requests for the other paragraphs, or are you worried that it will create merge conflicts?  If the edited sections do not overlap, it may be safe to make more changes or require only simple merge conflict resolution.

**Comment by AlexanderTitus** [comment]
Thanks @agitter - yes, we were concerned about the merge conflicts. The sections do not overlap, so we will submit and handle the conflicts later. 

@jlevy44 and @Christensen-Lab, lets go ahead with our other PRs.

**Comment by lanagarmire** [comment]
I will take a look this afternoon if i get time.

It is a snow storm here.

**Comment by jlevy44** [comment]
Thanks @lanagarmire . We appreciate the help.

Also will be adding this paper to our later PRs: https://ieeexplore.ieee.org/abstract/document/8621365

**Comment by jlevy44** [comment]
Hey everyone.

Unless if anything changes, I think I'm going to submit another PR with our entire proposed section very soon (within a week or 2). We can probably go ahead and close this PR.

**Comment by evancofer** [comment]
@jlevy44 Okay, I'll go ahead and close it.

**Comment by jlevy44** [comment]
@christensen-lab @christensen-lab-Dartmouth

**Pull request closed without merging**
