### PR TITLE
Improve affiliation formatting

### PR DESCRIPTION
**Pull request by dhimmel**
https://github.com/greenelab/deep-review/issues/516#issuecomment-304100123

### CODE REVIEW

**Comment by dhimmel** [comment]
Do you generate this author list in an automated way?

It's probably just worth automating this in the build using jinja2.

**Comment by agitter** [comment]
@dhimmel Semi-automated, in the sense that I didn't have time to handle all the special cases.  To do it properly, we'd need to covert the author table to tsv and read it when we build.

**Comment by agitter** [comment]
@dhimmel As long as we're making manual adjustments, should we take care of [this](https://github.com/greenelab/deep-review/pull/508#issuecomment-304092267) as well?

During revision I'd be up for fully-automating the author list.  I'm completely out of time to work on this now though.

**Comment by dhimmel** [comment]
> As long as we're making manual adjustments, should we take care of this as well?

See https://github.com/greenelab/deep-review/pull/517/commits/3572e91baecb42d8b0fb2cf8f778ead9fb9fbaba

**Comment by dhimmel** [comment]
> During revision I'd be up for fully-automating the author list. I'm completely out of time to work on this now though.

Okay sounds good. Let's automate later, but having done this PR manually, I think there's an important need for automation.

**Comment by agitter** [comment]
> Okay sounds good. Let's automate later, but having done this PR manually, I think there's an important need for automation.

Completely agree.  Once we're ready to move to the automated process, I can help write the code and harden the script I wrote.  We don't want to make manual adjustments more than once.

**Comment by agitter** [comment]
I'm merging.  @gailrosen this fixes the affiliation you noted in #508.

**Pull request merged**
