### PR TITLE
Fix styles & spelling

### PR DESCRIPTION
**Pull request by agapow**
Minor style and spelling fixes as per #391 

"significant" turned out to be a much abused term in the ms, couldn't fix all of them.

Note that for some odd reason, my abstract commits are bound up in this and I can't get git to understand they're not. Can you merge and ignore the changes to the abstract?

### CODE REVIEW

**Comment by agitter** [comment]
#399 created intro conflicts.  We'll have to see how bad they are.

**Comment by agitter** [comment]
I'm not sure what's going on with the abstract.  It looks like it requires a manual merge.  Can you get a clean copy with `git checkout sections/01_abstract.md` and then push again?

**Comment by agapow** [comment]
Spent a couple of hours yesterday trying to work out what was going on with my repo but you're right, I'll do a pull and see if that fixes it.

**Comment by agitter** [comment]
Good, that worked.  I'll review once more and merge.

**Pull request merged**
