### PR TITLE
Update DOI of published paper

### PR DESCRIPTION
**Pull request by agitter**
Will merge myself once the build passes

### CODE REVIEW

**Comment by agitter** [comment]
@dhimmel I can't figure out why the build failed with an error about `@tag:Soueidan`.  The DOI in `tags.tsv` is `doi:10.1515/metgen-2016-00011`, and I can resolve that at www.doi.org.

**Comment by dhimmel** [comment]
There's some sort of upstream issue, since

```sh
curl --location \
  --header "Accept: application/vnd.citationstycation/rdf+xml" \
  https://doi.org/10.1515/metgen-2016-0001
```

returns `No acceptable resource available.` See also https://github.com/greenelab/deep-review/pull/303#issuecomment-293071025.

The metadata for that study is showing up [on Crossref](https://search.crossref.org/?q=10.1515%2Fmetgen-2016-0001).

Usually the metadata caching hides these temperamental failures, but I reset the cache for the `citation_id` updates.

**Comment by agitter** [comment]
Thanks for investigating.  Because the issue isn't related to the DOI I changed, I'll merge this.

**Comment by dhimmel** [comment]
> Thanks for investigating. Because the issue isn't related to the DOI I changed, I'll merge this.

Yep that's what we'll have to do until this issue is resolved.

**Pull request merged**
