### PR TITLE
Enable manual citeproc JSON for references

### PR DESCRIPTION
**Pull request by dhimmel**

### CODE REVIEW

**Comment by dhimmel** [comment]
@agitter here's the PDF I built from https://github.com/greenelab/deep-review/pull/509/commits/26c71f41c57b2c1c03e4bb3aefc91c65eb54c37e if you want to check that the overrides are working: [deep-review.pdf](https://github.com/greenelab/deep-review/files/1026238/deep-review.pdf)

**Comment by dhimmel** [comment]
Let's merge this before #510. I don't think there will be an interaction, but I should probably rebase #510 once this is merged to be safe.

@agitter I'd like to merge soon. Let me know if it looks good to you.

**Comment by agitter** [comment]
Sounds good. I've been sitting in meetings today, but I'll review and merge
tonight.  I'll make a separate pull request for the remaining URL
corrections.

**Comment by agitter** [comment]
@dhimmel I reviewed these and made minor changes.  It's ready to merge now.  I'll let you do it so you can coordinate with #510.

I'm working on the last set of problematic documents in #381, which will close that issue.

**Pull request merged**
